[settings.meta]
id = "097a9679-47d2-451c-9821-2c0c72eb4011"

[settings.app]
zookeeper_mode = "thoughtful"

[settings.modeling]
fixed_size_grid = false

[settings.debug]
show_modeling_machine_state = true
show_panel = true

[cloud."zoo.dev"]
project_id = "621bc370-c2b9-4a81-88b2-167ac4a8ac59"
